apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sq
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
  labels:
    ingress: sq
spec:
  rules:
    - host: dmeppiel.eu.ngrok.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ce-lts-sonarqube
              port:
                name: http
    # define below the local adress where the service can be reached, the one added to your /etc/hosts
    - host: my.sonarqube.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ce-lts-sonarqube
              port:
                name: http