kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-data-volume
  labels:
    app: sq
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql-sq/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-data-claim
  labels:
    app: sq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi