---
# Source: sonarqube/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ce-lts-postgresql
  labels:
    app: postgresql
    chart: postgresql-8.6.4
    release: "ce-lts"
    heritage: "Helm"
type: Opaque
data:
  postgresql-password: "c29uYXJQYXNz"
