---
# Source: sonarqube/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ce-lts-sonarqube-config
  labels:
    app: sonarqube
    chart: sonarqube-1.0.4
    release: ce-lts
    heritage: Helm
data:
